# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BOOGIE_EXE: "viper_tools/boogie/Binaries/Boogie"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Get Viper tools
      run: |
        curl https://github.com/viperproject/viper-ide/releases/download/v-2021-08-03-0738/ViperToolsLinux.zip -Lo ViperToolsLinux.zip
        unzip ViperToolsLinux.zip -d viper_tools
    - name: Install nagini
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .
    - name: Test with pytest
      run: |
        pytest src/nagini_translation/tests.py --silicon --carbon
